name = "pmu-sport-app"
compatibility_date = "2023-12-01"

# Configuration pour le développement local
[dev]
port = 8788

# Configuration de la base de données D1
[[d1_databases]]
binding = "DB"                # Nom de la variable d'environnement
database_name = "pmu-sport-db"    # Nom de la base de données
database_id = "local"         # ID pour le développement local
